<?php

namespace App\Filament\Resources\ReportGenerations\Tables;

use App\Enums\ReportGenerationStatus;
use App\Enums\ReportType;
use App\Enums\RoleName;
use App\Models\ReportGeneration;
use Filament\Actions\Action;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;

class ReportGenerationsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->defaultSort('requested_at', 'desc')
            ->columns([
                TextColumn::make('report_type')
                    ->label('Report')
                    ->badge()
                    ->formatStateUsing(fn (ReportType | string | null $state): string => $state instanceof ReportType
                        ? $state->label()
                        : str($state ?? 'N/A')->headline()->toString())
                    ->color('gray')
                    ->sortable(),
                TextColumn::make('status')
                    ->badge()
                    ->formatStateUsing(fn (ReportGenerationStatus | string | null $state): string => $state instanceof ReportGenerationStatus
                        ? str($state->value)->headline()->toString()
                        : str($state ?? 'N/A')->headline()->toString())
                    ->color(fn (ReportGenerationStatus | string | null $state): string => match ($state instanceof ReportGenerationStatus ? $state : ($state ? ReportGenerationStatus::from($state) : null)) {
                        ReportGenerationStatus::Pending => 'warning',
                        ReportGenerationStatus::Completed => 'success',
                        ReportGenerationStatus::Failed => 'danger',
                        default => 'gray',
                    })
                    ->sortable(),
                TextColumn::make('selection_summary')
                    ->label('Scope')
                    ->searchable(),
                TextColumn::make('requested_by_name')
                    ->label('Generated by')
                    ->searchable()
                    ->visible(fn (): bool => auth()->user()?->hasRole(RoleName::SuperAdmin->value) ?? false),
                TextColumn::make('requested_by_email')
                    ->label('Email')
                    ->searchable()
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->visible(fn (): bool => auth()->user()?->hasRole(RoleName::SuperAdmin->value) ?? false),
                TextColumn::make('file_name')
                    ->label('File')
                    ->searchable()
                    ->toggleable(),
                TextColumn::make('requested_at')
                    ->label('Requested at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('completed_at')
                    ->label('Completed at')
                    ->dateTime()
                    ->sortable()
                    ->placeholder('Pending'),
                TextColumn::make('error_message')
                    ->limit(40)
                    ->tooltip(fn (ReportGeneration $record): ?string => $record->error_message)
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                SelectFilter::make('report_type')
                    ->options([
                        ReportType::Federation->value => ReportType::Federation->label(),
                        ReportType::Team->value => ReportType::Team->label(),
                    ]),
                SelectFilter::make('status')
                    ->options([
                        ReportGenerationStatus::Pending->value => 'Pending',
                        ReportGenerationStatus::Completed->value => 'Completed',
                        ReportGenerationStatus::Failed->value => 'Failed',
                    ]),
                SelectFilter::make('user')
                    ->relationship('user', 'name')
                    ->searchable()
                    ->preload()
                    ->visible(fn (): bool => auth()->user()?->hasRole(RoleName::SuperAdmin->value) ?? false),
            ])
            ->recordActions([
                Action::make('openReport')
                    ->label('Open report')
                    ->icon('heroicon-o-arrow-top-right-on-square')
                    ->color('primary')
                    ->url(fn (ReportGeneration $record): ?string => $record->getFileUrl(), shouldOpenInNewTab: true)
                    ->visible(fn (ReportGeneration $record): bool => filled($record->getFileUrl()) && $record->status === ReportGenerationStatus::Completed),
            ]);
    }
}
